name: On pull request

on:
  push:
#  pull_request:
#    branches:
#      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      max-parallel: 3
      matrix:
        php:
          - 7.2
#          - 7.3
#          - 7.4
#          - 8.0
#          - 8.1
        composer: 
          - 2  
    name: Test - php:${{ matrix.php }}; composer:${{ matrix.composer }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, gd, pdo_mysql, json, mbstring, pcre, session
          ini-values: post_max_size=256M
          coverage: none
          tools: composer:v${{ matrix.composer }}
      - name: Composer validate
        run: composer validate --strict --no-check-lock
      - name: Install Composer dependencies (with dev)
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
      - name: Run benchmark
        run: php vendor/bin/phpbench run --report=all
        shell: bash
